import { createSlice } from "@reduxjs/toolkit";
import { images } from "../../assets/images";

const products = [
  {
    id: 1,
    name: "Harry Potter",
    author: "J.K. Rowling",
    quantity: 3,
    image: images.book,
    featured: true,
  },
  {
    id: 2,
    name: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    quantity: 5,
    image: images.book,
    featured: false,
  },
  {
    id: 3,
    name: "To Kill a Mockingbird",
    author: "Harper Lee",
    quantity: 7,
    image: images.book,
    featured: true,
  },
  {
    id: 4,
    name: "1984",
    author: "George Orwell",
    quantity: 2,
    image: images.book,
    featured: false,
  },
  {
    id: 5,
    name: "The Catcher in the Rye",
    author: "J.D. Salinger",
    quantity: 4,
    image: images.book,
    featured: true,
  },
  {
    id: 6,
    name: "Pride and Prejudice",
    author: "Jane Austen",
    quantity: 6,
    image: images.book,
    featured: false,
  },
  {
    id: 7,
    name: "The Hobbit",
    author: "J.R.R. Tolkien",
    quantity: 8,
    image: images.book,
    featured: true,
  },
  {
    id: 8,
    name: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    quantity: 1,
    image: images.book,
    featured: false,
  },
  {
    id: 9,
    name: "The Alchemist",
    author: "Paulo Coelho",
    quantity: 9,
    image: images.book,
    featured: true,
  },
  {
    id: 10,
    name: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    quantity: 5,
    image: images.book,
    featured: false,
  },
  {
    id: 11,
    name: "Brave New World",
    author: "Aldous Huxley",
    quantity: 3,
    image: images.book,
    featured: true,
  },
  {
    id: 12,
    name: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    quantity: 7,
    image: images.book,
    featured: false,
  },
  {
    id: 13,
    name: "Moby-Dick",
    author: "Herman Melville",
    quantity: 4,
    image: images.book,
    featured: true,
  },
  {
    id: 14,
    name: "Frankenstein",
    author: "Mary Shelley",
    quantity: 2,
    image: images.book,
    featured: false,
  },
  {
    id: 15,
    name: "War and Peace",
    author: "Leo Tolstoy",
    quantity: 6,
    image: images.book,
    featured: true,
  },
  {
    id: 16,
    name: "The Odyssey",
    author: "Homer",
    quantity: 3,
    image: images.book,
    featured: false,
  },
  {
    id: 17,
    name: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    quantity: 8,
    image: images.book,
    featured: true,
  },
  {
    id: 18,
    name: "Jane Eyre",
    author: "Charlotte Brontë",
    quantity: 1,
    image: images.book,
    featured: false,
  },
  {
    id: 19,
    name: "Dracula",
    author: "Bram Stoker",
    quantity: 9,
    image: images.book,
    featured: true,
  },
  {
    id: 20,
    name: "Wuthering Heights",
    author: "Emily Brontë",
    quantity: 5,
    image: images.book,
    featured: false,
  },
  {
    id: 21,
    name: "Don Quixote",
    author: "Miguel de Cervantes",
    quantity: 3,
    image: images.book,
    featured: true,
  },
  {
    id: 22,
    name: "Les Misérables",
    author: "Victor Hugo",
    quantity: 7,
    image: images.book,
    featured: false,
  },
  {
    id: 23,
    name: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    quantity: 4,
    image: images.book,
    featured: true,
  },
  {
    id: 24,
    name: "Anna Karenina",
    author: "Leo Tolstoy",
    quantity: 2,
    image: images.book,
    featured: false,
  },
  {
    id: 25,
    name: "The Grapes of Wrath",
    author: "John Steinbeck",
    quantity: 6,
    image: images.book,
    featured: true,
  },
  {
    id: 26,
    name: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    quantity: 8,
    image: images.book,
    featured: false,
  },
  {
    id: 27,
    name: "Great Expectations",
    author: "Charles Dickens",
    quantity: 1,
    image: images.book,
    featured: true,
  },
  {
    id: 28,
    name: "A Tale of Two Cities",
    author: "Charles Dickens",
    quantity: 9,
    image: images.book,
    featured: false,
  },
  {
    id: 29,
    name: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    quantity: 5,
    image: images.book,
    featured: true,
  },
  {
    id: 30,
    name: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    quantity: 3,
    image: images.book,
    featured: false,
  },
];

const productsSlice = createSlice({
  name: "products",
  initialState: products,
  reducers: {
    populateProducts(state, action) {
      state = action.payload;
    },
  },
});

export const productsActions = productsSlice.actions;
export default productsSlice;
